version: "3.9"

services:
  backend:
    build: ./muiServer
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_USER: testuser
      DB_PASSWORD: test123
      DB_NAME: testdb
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - "./muiServer/db/init.sql:/docker-entrypoint-initdb.d/init.sql"
  frontend:
    build: ./muiDemo
    ports: 
      - "5173:4173"
    depends_on:
      - backend
