name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -name: checkout code
      uses: actions/checkout@v4

      -name: show environment
      run: |
      uname -a
      docker --version
      docker-compose --version

      -name: Build docker image
      run: docker-compose build

      -name: start containers
      run: docker-compose up -d

      -name: show running containers
      run: docker ps

      -name: stop containers
      run: docker-compose down

